# Generated by Django 5.2.12 on 2026-03-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
